apiVersion: dicode/v1
kind: TaskSet
metadata:
  name: buildin
spec:
  entries:
    tray:
      ref:
        path: ./tray/task.yaml

    notifications:
      ref:
        path: ./notify/task.yaml

    alert:
      ref:
        path: ./alert/task.yaml

    webui:
      ref:
        path: ./webui/task.yaml

    temp-cleanup:
      ref:
        path: ./temp-cleanup/task.yaml

    ai-agent:
      ref:
        path: ./ai-agent/task.yaml

    auth-start:
      ref:
        path: ./auth-start/task.yaml

    auth-relay:
      ref:
        path: ./auth-relay/task.yaml
