// Protocol schema for the dicode relay WebSocket tunnel.
//
// Single source of truth, generated on both sides:
//   - dicode-core (Go)    via protoc-gen-go → pkg/relay/pb/*.pb.go
//   - dicode-relay (Node) via protoc-gen-es → src/relay/pb/*.ts
//
// Wire format is JSON (WebSocket text frames). protojson (Go) and
// @bufbuild/protobuf's fromJson/toJson (Node) produce matching output.
//
// Protocol version: 3 (first generated-from-proto release). Bumping from v2
// is mandatory because two on-wire shapes changed:
//   - headers: previously a JSON object with string-array values, now nested
//     through HeaderValues. Proto3 maps cannot hold repeated values directly.
//   - timestamp: kept as int32 to keep protojson emitting it as a JSON number
//     instead of a quoted string (its default encoding for int64).
//
// Both sides MUST reject connections where the peer advertises protocol < 3.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerMessage is any message the relay server sends to the daemon.
// Wire form: a JSON object with one key identifying the variant, e.g.
//
//	{"challenge": {"nonce": "..."}}.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerMessage_Challenge
	//	*ServerMessage_Welcome
	//	*ServerMessage_Error
	//	*ServerMessage_Request
	Kind          isServerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetKind() isServerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerMessage) GetChallenge() *Challenge {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

type isServerMessage_Kind interface {
	isServerMessage_Kind()
}

type ServerMessage_Challenge struct {
	Challenge *Challenge `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"`
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,2,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerMessage_Request struct {
	Request *Request `protobuf:"bytes,4,opt,name=request,proto3,oneof"`
}

func (*ServerMessage_Challenge) isServerMessage_Kind() {}

func (*ServerMessage_Welcome) isServerMessage_Kind() {}

func (*ServerMessage_Error) isServerMessage_Kind() {}

func (*ServerMessage_Request) isServerMessage_Kind() {}

// ClientMessage is any message the daemon sends to the relay server.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_Response
	Kind          isClientMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMessage) GetKind() isClientMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Kind.(*ClientMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isClientMessage_Kind interface {
	isClientMessage_Kind()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Kind() {}

func (*ClientMessage_Response) isClientMessage_Kind() {}

// Challenge is the first frame the server sends: a 32-byte random nonce
// hex-encoded (64 lowercase hex chars).
type Challenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *Challenge) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// Hello is the daemon's handshake reply. The daemon signs
// sha256(nonce_bytes || timestamp_be_uint64) with its ECDSA P-256 signing key.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hex(sha256(uncompressed_pubkey)) — 64 lowercase hex chars.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Base64 std-encoded 65-byte uncompressed P-256 public key (0x04 || X || Y).
	// Used for ECDSA verification (WSS handshake + /auth/:provider sigs).
	Pubkey string `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// Base64 std-encoded 65-byte uncompressed P-256 public key (0x04 || X || Y).
	// Used as the ECIES recipient on OAuth token delivery (dicode-core#104).
	// Required — every daemon now ships with a split sign/decrypt identity.
	DecryptPubkey string `protobuf:"bytes,3,opt,name=decrypt_pubkey,json=decryptPubkey,proto3" json:"decrypt_pubkey,omitempty"`
	// Base64 std-encoded ECDSA P-256 ASN.1 DER signature.
	Sig string `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	// Unix timestamp in seconds. int32 keeps the JSON encoding a number.
	Timestamp     int32 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Hello) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Hello) GetDecryptPubkey() string {
	if x != nil {
		return x.DecryptPubkey
	}
	return ""
}

func (x *Hello) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

func (x *Hello) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Welcome acknowledges a successful handshake and hands the daemon its
// publicly reachable tunnel URL plus the broker's long-lived signing pubkey
// for TOFU pinning.
type Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full WSS URL for this client, e.g. wss://relay.dicode.app/u/<uuid>/hooks/
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Base64-encoded SPKI DER public key the broker uses to sign delivery
	// envelopes. Absent for brokers that don't support OAuth delivery.
	BrokerPubkey *string `protobuf:"bytes,2,opt,name=broker_pubkey,json=brokerPubkey,proto3,oneof" json:"broker_pubkey,omitempty"`
	// Protocol version announced by the broker. v3 means "types generated from
	// proto". Daemons that require >= 3 for OAuth read this on welcome.
	Protocol      *int32 `protobuf:"varint,3,opt,name=protocol,proto3,oneof" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Welcome) GetBrokerPubkey() string {
	if x != nil && x.BrokerPubkey != nil {
		return *x.BrokerPubkey
	}
	return ""
}

func (x *Welcome) GetProtocol() int32 {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return 0
}

// Error is any server-side rejection mid-session (bad signature, stale
// timestamp, registry conflict, etc.). After sending Error the server closes
// the connection.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request is an inbound HTTP request forwarded to the daemon.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv4 used to correlate the response.
	Id      string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method  string                   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path    string                   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers map[string]*HeaderValues `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Base64-encoded request body bytes.
	Body          string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Response is the daemon's reply to a forwarded request.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches the `id` from the corresponding Request.
	Id      string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status  int32                    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Base64-encoded response body bytes.
	Body          string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// HeaderValues wraps a list of strings so it can be the value type of a
// proto3 map (which does not allow repeated values directly). Both
// protojson and protobuf-es emit the inner `values` field on the wire.
type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{8}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// OAuthTokenDelivery is the body of the `/hooks/oauth-complete` webhook the
// broker forwards to the daemon after a successful OAuth exchange. It is
// transported inside a Request.body (base64-encoded JSON); this message type
// itself is not a ServerMessage variant.
//
// The ciphertext has the 16-byte AES-GCM authentication tag appended; the
// daemon must split the last 16 bytes off before passing to aesGCM.Open.
type OAuthTokenDelivery struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Base64-encoded uncompressed P-256 ephemeral public key (65 bytes).
	EphemeralPubkey string `protobuf:"bytes,2,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"`
	// Base64-encoded ciphertext with auth tag appended.
	Ciphertext string `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// Base64-encoded 12-byte AES-GCM nonce (IV).
	Nonce string `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Base64-encoded ECDSA P-256 signature over
	// sha256(session_id || ephemeral_pubkey || ciphertext || nonce). Signed by
	// the broker's long-lived key announced in Welcome.broker_pubkey.
	BrokerSig     *string `protobuf:"bytes,5,opt,name=broker_sig,json=brokerSig,proto3,oneof" json:"broker_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthTokenDelivery) Reset() {
	*x = OAuthTokenDelivery{}
	mi := &file_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthTokenDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthTokenDelivery) ProtoMessage() {}

func (x *OAuthTokenDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthTokenDelivery.ProtoReflect.Descriptor instead.
func (*OAuthTokenDelivery) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{9}
}

func (x *OAuthTokenDelivery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OAuthTokenDelivery) GetEphemeralPubkey() string {
	if x != nil {
		return x.EphemeralPubkey
	}
	return ""
}

func (x *OAuthTokenDelivery) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *OAuthTokenDelivery) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *OAuthTokenDelivery) GetBrokerSig() string {
	if x != nil && x.BrokerSig != nil {
		return *x.BrokerSig
	}
	return ""
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\x0fdicode.relay.v1\"\xef\x01\n" +
	"\rServerMessage\x12:\n" +
	"\tchallenge\x18\x01 \x01(\v2\x1a.dicode.relay.v1.ChallengeH\x00R\tchallenge\x124\n" +
	"\awelcome\x18\x02 \x01(\v2\x18.dicode.relay.v1.WelcomeH\x00R\awelcome\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x16.dicode.relay.v1.ErrorH\x00R\x05error\x124\n" +
	"\arequest\x18\x04 \x01(\v2\x18.dicode.relay.v1.RequestH\x00R\arequestB\x06\n" +
	"\x04kind\"\x80\x01\n" +
	"\rClientMessage\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.dicode.relay.v1.HelloH\x00R\x05hello\x127\n" +
	"\bresponse\x18\x02 \x01(\v2\x19.dicode.relay.v1.ResponseH\x00R\bresponseB\x06\n" +
	"\x04kind\"!\n" +
	"\tChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"\x8a\x01\n" +
	"\x05Hello\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\tR\x06pubkey\x12%\n" +
	"\x0edecrypt_pubkey\x18\x03 \x01(\tR\rdecryptPubkey\x12\x10\n" +
	"\x03sig\x18\x04 \x01(\tR\x03sig\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x05R\ttimestamp\"\x85\x01\n" +
	"\aWelcome\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12(\n" +
	"\rbroker_pubkey\x18\x02 \x01(\tH\x00R\fbrokerPubkey\x88\x01\x01\x12\x1f\n" +
	"\bprotocol\x18\x03 \x01(\x05H\x01R\bprotocol\x88\x01\x01B\x10\n" +
	"\x0e_broker_pubkeyB\v\n" +
	"\t_protocol\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf5\x01\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12?\n" +
	"\aheaders\x18\x04 \x03(\v2%.dicode.relay.v1.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x1aY\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.dicode.relay.v1.HeaderValuesR\x05value:\x028\x01\"\xe3\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.dicode.relay.v1.Response.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x1aY\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.dicode.relay.v1.HeaderValuesR\x05value:\x028\x01\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xc7\x01\n" +
	"\x12OAuthTokenDelivery\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10ephemeral_pubkey\x18\x02 \x01(\tR\x0fephemeralPubkey\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\tR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12\"\n" +
	"\n" +
	"broker_sig\x18\x05 \x01(\tH\x00R\tbrokerSig\x88\x01\x01B\r\n" +
	"\v_broker_sigB/Z-github.com/dicode/dicode/pkg/relay/pb;relaypbb\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_relay_proto_goTypes = []any{
	(*ServerMessage)(nil),      // 0: dicode.relay.v1.ServerMessage
	(*ClientMessage)(nil),      // 1: dicode.relay.v1.ClientMessage
	(*Challenge)(nil),          // 2: dicode.relay.v1.Challenge
	(*Hello)(nil),              // 3: dicode.relay.v1.Hello
	(*Welcome)(nil),            // 4: dicode.relay.v1.Welcome
	(*Error)(nil),              // 5: dicode.relay.v1.Error
	(*Request)(nil),            // 6: dicode.relay.v1.Request
	(*Response)(nil),           // 7: dicode.relay.v1.Response
	(*HeaderValues)(nil),       // 8: dicode.relay.v1.HeaderValues
	(*OAuthTokenDelivery)(nil), // 9: dicode.relay.v1.OAuthTokenDelivery
	nil,                        // 10: dicode.relay.v1.Request.HeadersEntry
	nil,                        // 11: dicode.relay.v1.Response.HeadersEntry
}
var file_relay_proto_depIdxs = []int32{
	2,  // 0: dicode.relay.v1.ServerMessage.challenge:type_name -> dicode.relay.v1.Challenge
	4,  // 1: dicode.relay.v1.ServerMessage.welcome:type_name -> dicode.relay.v1.Welcome
	5,  // 2: dicode.relay.v1.ServerMessage.error:type_name -> dicode.relay.v1.Error
	6,  // 3: dicode.relay.v1.ServerMessage.request:type_name -> dicode.relay.v1.Request
	3,  // 4: dicode.relay.v1.ClientMessage.hello:type_name -> dicode.relay.v1.Hello
	7,  // 5: dicode.relay.v1.ClientMessage.response:type_name -> dicode.relay.v1.Response
	10, // 6: dicode.relay.v1.Request.headers:type_name -> dicode.relay.v1.Request.HeadersEntry
	11, // 7: dicode.relay.v1.Response.headers:type_name -> dicode.relay.v1.Response.HeadersEntry
	8,  // 8: dicode.relay.v1.Request.HeadersEntry.value:type_name -> dicode.relay.v1.HeaderValues
	8,  // 9: dicode.relay.v1.Response.HeadersEntry.value:type_name -> dicode.relay.v1.HeaderValues
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	file_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerMessage_Challenge)(nil),
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Request)(nil),
	}
	file_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_Response)(nil),
	}
	file_relay_proto_msgTypes[4].OneofWrappers = []any{}
	file_relay_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
