// tray/task.ts — System tray daemon for dicode.
//
// Uses a pre-compiled native helper binary (systray-portable) that
// communicates with the Deno process over stdin/stdout JSON.
// No CGO, no GTK, no fyne dependency.

import Systray, { type MenuItem } from "./systray/mod.ts";

// ── icon ─────────────────────────────────────────────────────────────────────
//
// 32×32 PNG: purple background (#7c3aed) with a white ⚡ bolt drawn as two
// diagonal bars — matches the icon generated by pkg/tray/icon.go.
//
// Generated offline with the same algorithm as icon.go and base64-encoded so
// this file has zero external asset dependencies.

// 32×32 PNG: purple background (#7c3aed) with a white ⚡ bolt.
// Generated from the same pixel algorithm as the removed pkg/tray/icon.go.
const ICON_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAg0lEQVR4nGKpsXrLQEvARFPTh4UFLJRobj4qBGfXWr/DqmYQBxExzh/EPiDS+YPVB8Q7f1D6gCTnDz4fkOp8fEUFGWZhBST4gDwrGfFUOFTxxIBGMrKrkX1DNQuoAghYQLknBtoHlHtiEPiAQk8MDh9Q4gl8RQVVwKAJosFrASAAAP///MwvLg37TZMAAAAASUVORK5CYII=";

export default async function main({ params }: DicodeSdk) {
  // ── platform browser-open helper ─────────────────────────────────────────────

  async function openBrowser(url: string): Promise<void> {
    const os = Deno.build.os;
    let cmd: string[];
    if (os === "linux") {
      cmd = ["xdg-open", url];
    } else if (os === "darwin") {
      cmd = ["open", url];
    } else if (os === "windows") {
      cmd = ["rundll32", "url.dll,FileProtocolHandler", url];
    } else {
      console.warn(`openBrowser: unsupported OS "${os}", cannot open ${url}`);
      return;
    }

    try {
      const proc = new Deno.Command(cmd[0], { args: cmd.slice(1) });
      await proc.spawn().status;
    } catch (err) {
      console.warn(`openBrowser: failed to open ${url}: ${err}`);
    }
  }

  // ── tray setup ───────────────────────────────────────────────────────────────

  // Resolve dashboard port: prefer the DICODE_PORT env var set by dicoded;
  // fall back to 8080.
  const port = parseInt(Deno.env.get("DICODE_PORT") ?? "8080", 10);
  const dashboardURL = `http://localhost:${port}`;

  const menuItems: MenuItem[] = [
    {
      title: "Open Dashboard",
      tooltip: dashboardURL,
      checked: false,
      enabled: true,
    },
    {
      title: "---", // separator (systray convention)
      tooltip: "",
      checked: false,
      enabled: true,
    },
    {
      title: "Quit dicode",
      tooltip: "Stop the dicode server",
      checked: false,
      enabled: true,
    },
  ];

  console.log("tray: starting system tray icon");

  const version = await params.get("tray_version") ?? undefined;

  const systray = new Systray({
    menu: {
      // icon is a base64-encoded PNG string; pass empty string to use the default
      // OS placeholder until ICON_BASE64 is populated (see TODO above).
      icon: ICON_BASE64,
      title: "dicode",
      tooltip: "dicode — automation server",
      items: menuItems,
    },
    debug: false,
    copyDir: true, // copy the native helper binary to a temp dir on first run
    version,
  });

  // ── event loop ───────────────────────────────────────────────────────────────
  //
  // systray.onClick delivers menu-item click events. We never return from this
  // loop; dicoded keeps the daemon alive and will restart it if it exits
  // unexpectedly (trigger.restart: always).

  // Wait for the binary to be downloaded, started, and ready.
  await systray.ready();

  systray.onClick((action) => {
    switch (action.item.title) {
      case "Open Dashboard":
        openBrowser(dashboardURL).catch((err) =>
          console.error(`tray: openBrowser error: ${err}`)
        );
        break;

      case "Quit dicode":
        console.log("tray: Quit clicked — sending SIGTERM to dicoded");
        systray.kill(false); // shut down the native helper without exiting Deno
        Deno.kill(Deno.ppid, "SIGTERM"); // signal dicoded to shut down gracefully
        break;

      default:
        // separators and unknown items are ignored
        break;
    }
  });

  // Keep the Deno event loop alive indefinitely so the daemon never exits on its
  // own.  dicoded's trigger.restart: always will relaunch it if something goes
  // wrong (e.g. the native helper crashes).
  await new Promise<never>((_resolve) => {});
}
