apiVersion: dicode/v1
kind: TaskSet
metadata:
  name: examples
spec:
  entries:
    tray:
      ref:
        path: ./tray/task.yaml
    hello-cron:
      ref:
        path: ./hello-cron/task.yaml
    github-stars-hook:
      ref:
        path: ./github-stars/task.yaml
      overrides:
        trigger:
          webhook: /hooks/examples/github-stars-hook
    github-stars:
      ref:
        path: ./github-stars/task.yaml
      overrides:
        notify:
          on_success: true  # silence success for this one task
          on_failure: true
    gmail-to-slack:
      ref:
        path: ./gmail-to-slack/task.yaml

    google-login:
      ref:
        path: ./google-login/task.yaml

    hello-docker:
      ref:
        path: ./hello-docker/task.yaml

    hello-podman:
      ref:
        path: ./hello-podman/task.yaml

    hello-python:
      ref:
        path: ./hello-python/task.yaml

    nginx-start:
      ref:
        path: ./nginx-start/task.yaml

    webhook-form:
      ref:
        path: ./webhook-form/task.yaml

    webhook-dashboard:
      ref:
        path: ./webhook-dashboard/task.yaml

    hello-webhook:
      ref:
        path: ./hello-webhook/task.yaml

    github-push-webhook:
      ref:
        path: ./github-push-webhook/task.yaml

    webui:
      ref:
        path: ./webui/task.yaml
