// Package onboarding handles the first-run experience when no dicode.yaml
// exists. It serves a wizard page in the browser that lets the user choose
// between local-only mode and git-backed mode, then generates a dicode.yaml.
//
// Flow:
//  1. main.go calls onboarding.Required(configPath) — returns true if no config
//  2. If required, start a temporary HTTP server on :8080 and open browser
//  3. User completes the wizard (local or git)
//  4. Wizard handler writes dicode.yaml and signals completion
//  5. main.go restarts with the new config
package onboarding

import (
	"os"
	"path/filepath"
)

// Required returns true if no config file exists at path and onboarding
// should be run before starting the main application.
func Required(configPath string) bool {
	_, err := os.Stat(configPath)
	return os.IsNotExist(err)
}

// Result holds the user's choices from the onboarding wizard.
type Result struct {
	Mode    Mode   // LocalOnly or Git
	GitURL  string // only set when Mode == Git
	GitAuth struct {
		Type     string // "token" | "ssh"
		TokenEnv string
	}
	TasksDir string // local tasks directory (always set)
	DataDir  string // dicode data directory
}

// Mode is the storage mode chosen during onboarding.
type Mode string

const (
	ModeLocalOnly Mode = "local"
	ModeGit       Mode = "git"
)

// DefaultLocalConfig returns a minimal dicode.yaml content for local-only mode.
func DefaultLocalConfig(tasksDir, dataDir string) string {
	return `# dicode configuration — local only mode
# Generated by dicode onboarding wizard.
# Add a git source later with: dicode task commit <id> --to <repo>

sources:
  - type: local
    path: ` + tasksDir + `
    watch: true

database:
  type: sqlite

server:
  port: 8080
  mcp: true
  tray: true

log_level: info
data_dir: ` + dataDir + `
`
}

// WriteConfig writes the generated config to configPath, creating parent
// directories as needed.
func WriteConfig(configPath, content string) error {
	if err := os.MkdirAll(filepath.Dir(configPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(configPath, []byte(content), 0644)
}
