package onboarding

import (
	"fmt"
	"io"
	"strings"
)

// Result captures the user's choices from either wizard surface, fed into
// RenderConfig to produce a ready-to-load dicode.yaml.
type Result struct {
	TaskSetsEnabled map[string]bool // keyed by TaskSetPreset.Name
	LocalTasksDir   string          // "" → omit local source
	DataDir         string
	Port            int
	Passphrase      string
}

// RenderConfig generates a dicode.yaml document from the wizard's Result.
// The output uses the new spec.entries shape: each source is an entry under
// spec.entries keyed by its name. The local tasks dir (if set) appears as a
// "local" entry pointing at the user's tasks directory.
func RenderConfig(r Result) string {
	var b strings.Builder

	b.WriteString(`# dicode configuration
# Generated by the first-run wizard. Edit and restart to apply changes.
#
# Path variables usable in any path field:
#   ${HOME}      — user home directory
#   ${CONFIGDIR} — directory containing this dicode.yaml file
#   ${DATADIR}   — resolved data_dir (default: ~/.dicode)

# ---------------------------------------------------------------------------
# Task sources — declared as spec.entries. Each entry key is the namespace
# for the tasks it contains. The ref block points at a taskset.yaml.
# ---------------------------------------------------------------------------
spec:
  entries:
`)

	for _, p := range TaskSetPresets {
		if !r.TaskSetsEnabled[p.Name] {
			continue
		}
		target := fmt.Sprintf("branch: %q", p.Branch)
		if p.Tag != "" {
			target = fmt.Sprintf("tag: %q", p.Tag)
		}
		fmt.Fprintf(&b, "    %s:\n      ref:\n        url: %q\n        %s\n        path: %q\n        poll_interval: 30s\n", p.Name, p.URL, target, p.EntryPath)
	}

	if r.LocalTasksDir != "" {
		fmt.Fprintf(&b, "    local:\n      ref:\n        path: %q\n        watch: true\n", r.LocalTasksDir)
	}

	b.WriteString(`
# ---------------------------------------------------------------------------
# Database — run history and task KV data.
# ---------------------------------------------------------------------------
database:
  type: sqlite
  path: ${DATADIR}/data.db

# ---------------------------------------------------------------------------
# Secrets — encrypted storage for API keys and tokens used by tasks.
# ---------------------------------------------------------------------------
secrets:
  providers:
    - type: local
    - type: env

# ---------------------------------------------------------------------------
# Web UI & API server
# ---------------------------------------------------------------------------
server:
`)
	fmt.Fprintf(&b, "  port: %d\n", r.Port)
	b.WriteString("  mcp: true\n")
	b.WriteString("  tray: true\n")
	b.WriteString("  auth: true\n")
	fmt.Fprintf(&b, "  secret: %q\n", r.Passphrase)

	b.WriteString(`
# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log_level: info
`)
	fmt.Fprintf(&b, "data_dir: %q\n", r.DataDir)

	return b.String()
}

// PrintSuccess writes the "setup complete" banner that shows the user the
// dashboard URL and the generated passphrase, exactly once. Called after
// the YAML has been written to disk on any wizard surface.
func PrintSuccess(out io.Writer, r Result, configPath string) {
	fmt.Fprintln(out, "━━━ dicode setup complete ━━━")
	fmt.Fprintln(out, "Config written to", configPath)
	fmt.Fprintf(out, "Dashboard: http://localhost:%d\n", r.Port)
	fmt.Fprintln(out, "Login passphrase (copy now, shown once):")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "    "+r.Passphrase)
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Store this somewhere safe. To change later: edit")
	fmt.Fprintln(out, "server.secret in your dicode.yaml and restart.")
	fmt.Fprintln(out, "━━━━━━━━━━━━━━━━━━━━━━━━━━━")
}
