package onboarding

import (
	"fmt"
	"io"
	"strings"
)

// Result captures the user's choices from either wizard surface, fed into
// RenderConfig to produce a ready-to-load dicode.yaml.
type Result struct {
	TaskSetsEnabled map[string]bool // keyed by TaskSetPreset.Name
	LocalTasksDir   string          // "" → omit local source
	DataDir         string
	Port            int
	Passphrase      string
}

// RenderConfig generates a dicode.yaml document from the wizard's Result.
// The output includes a commented header, the selected git sources, an
// optional local source, and server.auth + server.secret filled from the
// generated passphrase.
func RenderConfig(r Result) string {
	var b strings.Builder

	b.WriteString(`# dicode configuration
# Generated by the first-run wizard. Edit and restart to apply changes.
#
# Path variables usable in any path field:
#   ${HOME}      — user home directory
#   ${CONFIGDIR} — directory containing this dicode.yaml file
#   ${DATADIR}   — resolved data_dir (default: ~/.dicode)

# ---------------------------------------------------------------------------
# Task sources — where dicode looks for tasks.
# ---------------------------------------------------------------------------
sources:
`)

	for _, p := range TaskSetPresets {
		if !r.TaskSetsEnabled[p.Name] {
			continue
		}
		fmt.Fprintf(&b, `  - type: git
    name: %s
    url: %s
    branch: %s
    entry_path: %s
    poll_interval: 30s
`, p.Name, p.URL, p.Branch, p.EntryPath)
	}

	if r.LocalTasksDir != "" {
		fmt.Fprintf(&b, `  - type: local
    path: %s
    watch: true
`, r.LocalTasksDir)
	}

	b.WriteString(`
# ---------------------------------------------------------------------------
# Database — run history and task KV data.
# ---------------------------------------------------------------------------
database:
  type: sqlite
  path: ${DATADIR}/data.db

# ---------------------------------------------------------------------------
# Secrets — encrypted storage for API keys and tokens used by tasks.
# ---------------------------------------------------------------------------
secrets:
  providers:
    - type: local
    - type: env

# ---------------------------------------------------------------------------
# Web UI & API server
# ---------------------------------------------------------------------------
server:
`)
	fmt.Fprintf(&b, "  port: %d\n", r.Port)
	b.WriteString("  mcp: true\n")
	b.WriteString("  tray: true\n")
	b.WriteString("  auth: true\n")
	fmt.Fprintf(&b, "  secret: %q\n", r.Passphrase)

	b.WriteString(`
# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log_level: info
`)
	fmt.Fprintf(&b, "data_dir: %s\n", r.DataDir)

	return b.String()
}

// PrintSuccess writes the "setup complete" banner that shows the user the
// dashboard URL and the generated passphrase, exactly once. Called after
// the YAML has been written to disk on any wizard surface.
func PrintSuccess(out io.Writer, r Result, configPath string) {
	fmt.Fprintln(out, "━━━ dicode setup complete ━━━")
	fmt.Fprintln(out, "Config written to", configPath)
	fmt.Fprintf(out, "Dashboard: http://localhost:%d\n", r.Port)
	fmt.Fprintln(out, "Login passphrase (copy now, shown once):")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "    "+r.Passphrase)
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Store this somewhere safe. To change later: edit")
	fmt.Fprintln(out, "server.secret in your dicode.yaml and restart.")
	fmt.Fprintln(out, "━━━━━━━━━━━━━━━━━━━━━━━━━━━")
}
