import type { DicodeSdk } from "../sdk.ts";
// tray/task.ts — System tray daemon for dicode.
//
// Replaces pkg/tray/ (CGO, fyne.io/systray) with a pure Deno implementation.
// Option A from issue #59: deno.land/x/systray ships a pre-compiled native
// helper binary (systray-master / systray.exe) that communicates with the Deno
// process over stdin/stdout JSON, so there is no CGO or GTK dependency.
//
// TODO(#59): Verify the exact import path before shipping. At time of writing
// the canonical module is https://deno.land/x/systray@v0.0.2/mod.ts — check
// https://deno.land/x/systray for the latest version tag.
//
// References:
//   https://github.com/dicode-ayo/dicode-core/issues/59
//   https://github.com/zserge/lorca (inspiration)
//   https://github.com/getlantern/systray (Go helper, same binary approach)

import Systray, { type MenuItem } from "./systray/mod.ts";

// ── icon ─────────────────────────────────────────────────────────────────────
//
// 32×32 PNG: purple background (#7c3aed) with a white ⚡ bolt drawn as two
// diagonal bars — matches the icon generated by pkg/tray/icon.go.
//
// Generated offline with the same algorithm as icon.go and base64-encoded so
// this file has zero external asset dependencies.

const ICON_BASE64 =
  // 32×32 RGBA PNG, purple bg + white lightning bolt
  // To regenerate: run pkg/tray/icon.go's init() logic and base64-encode the output.
  // TODO(#59): Replace with the actual pre-generated base64 string once icon.go
  //            can be run standalone (or embed the PNG as a repo asset).
  "";

export default async function main({ log, params }: DicodeSdk) {
  // ── platform browser-open helper ─────────────────────────────────────────────

  async function openBrowser(url: string): Promise<void> {
    const os = Deno.build.os;
    let cmd: string[];
    if (os === "linux") {
      cmd = ["xdg-open", url];
    } else if (os === "darwin") {
      cmd = ["open", url];
    } else if (os === "windows") {
      cmd = ["rundll32", "url.dll,FileProtocolHandler", url];
    } else {
      log.warn(`openBrowser: unsupported OS "${os}", cannot open ${url}`);
      return;
    }

    try {
      const proc = new Deno.Command(cmd[0], { args: cmd.slice(1) });
      await proc.spawn().status;
    } catch (err) {
      log.warn(`openBrowser: failed to open ${url}: ${err}`);
    }
  }

  // ── tray setup ───────────────────────────────────────────────────────────────

  // Resolve dashboard port: prefer the DICODE_PORT env var set by dicoded;
  // fall back to 8080.
  const port = parseInt(Deno.env.get("DICODE_PORT") ?? "8080", 10);
  const dashboardURL = `http://localhost:${port}`;

  const menuItems: MenuItem[] = [
    {
      title: "Open Dashboard",
      tooltip: dashboardURL,
      checked: false,
      enabled: true,
    },
    {
      title: "---", // separator (systray convention)
      tooltip: "",
      checked: false,
      enabled: true,
    },
    {
      title: "Quit dicode",
      tooltip: "Stop the dicode server",
      checked: false,
      enabled: true,
    },
  ];

  await log.info("tray: starting system tray icon");

  const version = await params.get("tray_version") ?? undefined;

  const systray = new Systray({
    menu: {
      // icon is a base64-encoded PNG string; pass empty string to use the default
      // OS placeholder until ICON_BASE64 is populated (see TODO above).
      icon: ICON_BASE64,
      title: "dicode",
      tooltip: "dicode — automation server",
      items: menuItems,
    },
    debug: false,
    copyDir: true, // copy the native helper binary to a temp dir on first run
    version,
  });

  // ── event loop ───────────────────────────────────────────────────────────────
  //
  // systray.onClick delivers menu-item click events. We never return from this
  // loop; dicoded keeps the daemon alive and will restart it if it exits
  // unexpectedly (trigger.restart: always).

  // Wait for the binary to be downloaded, started, and ready.
  await systray.ready();

  systray.onClick((action) => {
    switch (action.item.title) {
      case "Open Dashboard":
        openBrowser(dashboardURL).catch((err) =>
          log.error(`tray: openBrowser error: ${err}`)
        );
        break;

      case "Quit dicode":
        log.info("tray: Quit clicked — exiting");
        systray.kill(); // sends exit to native helper, then calls Deno.exit()
        break;

      default:
        // separators and unknown items are ignored
        break;
    }
  });

  // Keep the Deno event loop alive indefinitely so the daemon never exits on its
  // own.  dicoded's trigger.restart: always will relaunch it if something goes
  // wrong (e.g. the native helper crashes).
  await new Promise<never>((_resolve) => {});
}
