{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dicode.fullname" . }}
  labels:
    {{- include "dicode.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret.values }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
{{- end }}
